name: Upload Update File

on:
  push:
    branches:
      - main

jobs:
  upload-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Read Version
      id: get_version
      run: |
        VERSION=$(ls build/ | awk -F'-v' '{print $2}' | head -n 1)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Upload to S3
      run: |
        aws s3 cp ./build/* s3://mask-ota/update-v${{ env.VERSION }}
        aws s3 cp ./build/* s3://mask-ota/update-latest

    - name: Update Versions Metadata
      run: |
        VERSION=${{ env.VERSION }}
        aws s3 cp s3://mask-ota/versions.json versions.json || echo '{"latest": "", "versions": {}}' > versions.json
        jq --arg version "$VERSION" --arg url "https://mask-ota.s3.amazonaws.com/update-v$VERSION" \
          '.latest = $version | .versions[$version] = $url' versions.json > updated_versions.json
        aws s3 cp updated_versions.json s3://mask-ota/versions.json
